[build]
builder = "nixpacks"
buildCommand = "npm install && npx puppeteer browsers install chrome && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 